### ISSUE TITLE
Deposit hover

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#115]
The deposit is the sum of the challenge reward bounty and the arbitration cost. ---> These are the funds users will have to deposit in order to make a submission into the list and also the amount that users will earn for a successful challenge. If the deposit is too low, incorrect submissions may not be flagged for dispute which could result in incorrect items being accepted in the list. If the deposit is too high challengers will be likely to catch most malicious submissions, but people will only rarely submit to your list (so you may end up having a list that is difficult to attack but largely empty).

<img width="263" alt="deposit hover" src="https://user-images.githubusercontent.com/16290963/84155036-34dfd500-aa3e-11ea-8183-36b2a85ab6c5.png">

**Comment by whwgeorge** [comment]
"These are the funds users will have to deposit in order to make a submission into the list and also the amount that users will earn for a successful challenge." I feel is confusing because these are two different amounts. 

Maybe: "These are the funds users will have to deposit in order to make a submission into the list, including the amount that users will earn for a successful challenge. If the deposit is too low, incorrect submissions may not be flagged for dispute which could result in incorrect items being accepted in the list. If the deposit is too high challengers will be likely to catch most malicious submissions, but people will only rarely submit to your list (so you may end up having a list that is difficult to attack but largely empty)."
