### ISSUE TITLE
Incorrect Challenge Compensation Hover

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#117]
@whwgeorge can you please write the little hover explainer text here? Explaining what this parameter is and what happens if it's too high/low.

See the hovers in other items for reference.

<img width="762" alt="incorrect challenge compensation" src="https://user-images.githubusercontent.com/16290963/84160720-e3871400-aa44-11ea-82fe-d0c4d957ffd4.png">

**Comment by whwgeorge** [comment]
This amount, which is included in the deposits that challengers must make, is given to the submitter in the event that the submission is challenged but ultimately is ruled to be correct. One typically wants Incorrect Challenge Compensation to be zero, because being on the list should be an adequate incentive for submitters. However, if you anticipate frivolous challenges being a problem, a higher Incorrect Challenge Compensation can help protect against this. If Incorrect Challenge Compensation is too high, users will be disincentivized from challenging and incorrect entries may make it onto the list unchallenged.
