### ISSUE TITLE
Challenge Period, Governor, Arbitrator Hovers

### ISSUE THREAD

**Issue by federicoast** [kleros/gtcr#119]
@whwgeorge can you please write the hover explainers for these?

![FireShot Capture 1067 - Kleros · Curate - https___curate kleros io_factory](https://user-images.githubusercontent.com/16290963/84161705-f3ebbe80-aa45-11ea-9266-431b612ab86f.jpg)

**Comment by whwgeorge** [comment]
Challenge Period Duration (hours): The length of time (in hours) that a submission can be challenged before it it automatically accepted onto the list and the submitter's deposit is refunded. 

(So we make clear in the description what the challenge period is.)

For the Governor, I think the current text is pretty good. It might be worth separating out the role of changing the governor from the other parameters so that users don't have to be too meta in their understanding. Maybe: 

"The address of the governor to use for this list. It can update parameters such as the challenge period duration, deposits, primary document, etc. This address can also be used to transfer the role of governor to another address. By default this is set to Kovan Kleros Governor."

The text on the arbitrator: "This is the contract address of the arbitrator that will resolve the disputes occurring in this list. By default it is set to Kleros, but you could use any other arbitrator complying with the ERC 792 standard." seems pretty okay to me. Maybe
"This is the contract address of the arbitrator that will resolve disputes regarding whether challenged submissions and challenged removal requests belong on this list. By default it is set to Kleros, but you could use any other arbitrator complying with the ERC 792 standard."

It is a bit cryptic if someone fell on this page without knowing the basics of how TCRs are supposed to work/what Kleros is, but that would be hard to explain in a tooltip.
