### ISSUE TITLE
Simplify Factory

### ISSUE THREAD

**Issue by mtsalenc** [kleros/gtcr#77]
- [x] By default, control submission, removal and challenge removal deposits together, with a slider.
- [x] By default submission challenge base deposit should be 0.
- [x] Replace sliders for number fields if the user sets the "Advanced Option"
- [x] Use a slider to select the number of jurors
- [x] Display a formula explaining how the total cost is calculated.
- [x] Set the default number of jurors to 3.
- [x] Move court selection out of the advanced section.
- [x] Submission Challenge Bounty (Given to successful challenger) + Arbitration fees (Fees paid to juror) = Submission Deposit (Amount put at stake by a submitter, given back if the item is accepted)
- [x] Removal Challenge Bounty (Given to successful challenger) + Arbitration fees (Fees paid to juror) = Removal Deposit (Amount put at stake by the party requesting the item to be removed, given back if the item is removed)
- [x] Incorrect challenge compensation (Given to the submitter when its submission in incorrectly challenged) + Arbitration fees (Fees paid to juror) = Challenger Deposit (Amount put )
- [x] Incorrect removal challenge compensation (Given to the party asking to remove an item when its request in incorrectly challenged) + Arbitration fees (Fees paid to juror) = Challenger Deposit

**Comment by whwgeorge** [comment]
Upon some further reflection, I think it makes sense to have Submission Deposit, Removal Deposit, and Challenge Removal Deposit all slide together/be the same by default, while Challenge Deposit is zero by default and not affected by the slider. (Rather than our previous discussions/the spec above that also Challenge Removal Deposit as zero and not affected by the slider.)
